export const typeList = ['Savings', 'Current'];
export const banksList = [
  {name: 'State Bank of India (SBI)'},
  {name: 'Punjab National Bank'},
  {name: 'Bank of Baroda'},
  {name: 'Canara Bank'},
  {name: 'Union Bank of India'},
  {name: 'Bank of India'},
  {name: 'Indian Bank'},
  {name: 'Central Bank of India'},
  {name: 'Bank of Maharashtra'},
  {name: 'UCO Bank'},
  {name: 'Punjab & Sind Bank'},
  {name: 'Indian Overseas Bank'},
  {name: 'Axis Bank'},
  {name: 'HDFC Bank'},
  {name: 'ICICI Bank'},
  {name: 'Kotak Mahindra Bank'},
  {name: 'IndusInd Bank'},
  {name: 'Yes Bank'},
  {name: 'IDFC FIRST Bank'},
  {name: 'Federal Bank'},
  {name: 'South Indian Bank'},
  {name: 'RBL Bank'},
  {name: 'Bandhan Bank'},
  {name: 'IDBI Bank'},
  {name: 'City Union Bank'},
  {name: 'Tamilnad Mercantile Bank'},
  {name: 'Karnataka Bank'},
  {name: 'Dhanlaxmi Bank'},
  {name: 'Jammu & Kashmir Bank'},
  {name: 'Nainital Bank'},
  {name: 'Saraswat Co-operative Bank'},
  {name: 'Shamrao Vithal Co-operative Bank'},
  {name: 'Abhyudaya Co-operative Bank'},
  {name: 'Bharat Co-operative Bank'},
  {name: 'Cosmos Co-operative Bank'},
  {name: 'TJSB Sahakari Bank'},
  {name: 'Punjab & Maharashtra Co-operative Bank'},
  {name: 'Standard Chartered Bank'},
  {name: 'Citibank'},
  {name: 'HSBC Bank'},
  {name: 'Deutsche Bank'},
  {name: 'DBS Bank'},
  {name: 'Barclays Bank'},
  {name: 'BNP Paribas'},
  {name: 'Bank of America'},
  {name: 'JPMorgan Chase Bank'},
  {name: 'Mizuho Bank'},
  {name: 'MUFG Bank'},
  {name: 'Sumitomo Mitsui Banking Corporation'},
  {name: 'Royal Bank of Scotland'},
  {name: 'Abu Dhabi Commercial Bank'},
  {name: 'Doha Bank'},
  {name: 'Qatar National Bank'},
  {name: 'First Abu Dhabi Bank'},
  {name: 'Mashreq Bank'},
  {name: 'Bank of Bahrain and Kuwait'},
  {name: 'Oman International Bank'},
  {name: 'Shinhan Bank'},
  {name: 'Woori Bank'},
  {name: 'Kookmin Bank'},
  {name: 'Industrial & Commercial Bank of China'},
  {name: 'China Construction Bank'},
  {name: 'Bank of China'},
  {name: 'Agricultural Bank of China'},
  {name: 'Australia and New Zealand Banking Group'},
  {name: 'Westpac Banking Corporation'},
  {name: 'Rabobank'},
  {name: 'Societe Generale'},
  {name: 'Credit Agricole Corporate & Investment Bank'},
  {name: 'UBS Bank'},
  {name: 'Credit Suisse'},
  {name: 'American Express Bank'},
  {name: 'Bank of Nova Scotia'},
  {name: 'State Bank of Mauritius'},
  {name: 'United Overseas Bank'},
  {name: 'Commonwealth Bank of Australia'},
  {name: 'HSBC Bank Oman'},
  {name: 'National Australia Bank'},
  {name: 'PT Bank Maybank Indonesia'},
  {name: 'Bangkok Bank'},
  {name: 'Krung Thai Bank'},
  {name: 'Bank of Ceylon'},
  {name: 'Hatton National Bank'},
  {name: 'Seylan Bank'},
  {name: 'National Development Bank'},
  {name: 'Commercial Bank of Ceylon'},
  {name: 'DFCC Bank'},
  {name: 'Sampath Bank'},
  {name: 'Nations Trust Bank'},
  {name: 'Union Bank of Colombo'},
  {name: 'Pan Asia Banking Corporation'},
  {name: 'Amana Bank'},
  {name: 'Cargills Bank'},
  {name: 'Axis Bank'},
  {name: 'HDFC Bank'},
  {name: 'ICICI Bank'},
  {name: 'Kotak Mahindra Bank'},
  {name: 'IndusInd Bank'},
  {name: 'Yes Bank'},
  {name: 'IDFC FIRST Bank'},
  {name: 'Federal Bank'},
  {name: 'South Indian Bank'},
  {name: 'RBL Bank'},
  {name: 'Bandhan Bank'},
  {name: 'IDBI Bank'},
  {name: 'City Union Bank'},
  {name: 'Tamilnad Mercantile Bank'},
  {name: 'Karnataka Bank'},
  {name: 'Dhanlaxmi Bank'},
  {name: 'Jammu & Kashmir Bank'},
  {name: 'Nainital Bank'},
  {name: 'Saraswat Co-operative Bank'},
  {name: 'Shamrao Vithal Co-operative Bank'},
  {name: 'Abhyudaya Co-operative Bank'},
  {name: 'Bharat Co-operative Bank'},
  {name: 'Cosmos Co-operative Bank'},
  {name: 'TJSB Sahakari Bank'},
  {name: 'Punjab & Maharashtra Co-operative Bank'},
  {name: 'Standard Chartered Bank'},
  {name: 'Citibank'},
  {name: 'HSBC Bank'},
  {name: 'Deutsche Bank'},
  {name: 'DBS Bank'},
  {name: 'Barclays Bank'},
  {name: 'BNP Paribas'},
  {name: 'Bank of America'},
  {name: 'JPMorgan Chase Bank'},
  {name: 'Mizuho Bank'},
  {name: 'MUFG Bank'},
  {name: 'Sumitomo Mitsui Banking Corporation'},
  {name: 'Royal Bank of Scotland'},
  {name: 'Abu Dhabi Commercial Bank'},
  {name: 'Doha Bank'},
  {name: 'Qatar National Bank'},
  {name: 'First Abu Dhabi Bank'},
  {name: 'Mashreq Bank'},
  {name: 'Mashreq Bank'},
  {name: 'Bank of Bahrain and Kuwait'},
  {name: 'Oman International Bank'},
  {name: 'Shinhan Bank'},
  {name: 'Woori Bank'},
  {name: 'Kookmin Bank'},
  {name: 'Industrial & Commercial Bank of China'},
  {name: 'China Construction Bank'},
  {name: 'Bank of China'},
  {name: 'Agricultural Bank of China'},
  {name: 'Australia and New Zealand Banking Group'},
  {name: 'Westpac Banking Corporation'},
  {name: 'Rabobank'},
  {name: 'Societe Generale'},
  {name: 'Credit Agricole Corporate & Investment Bank'},
  {name: 'UBS Bank'},
  {name: 'Credit Suisse'},
  {name: 'American Express Bank'},
  {name: 'Bank of Nova Scotia'},
  {name: 'State Bank of Mauritius'},
  {name: 'United Overseas Bank'},
  {name: 'Commonwealth Bank of Australia'},
  {name: 'HSBC Bank Oman'},
  {name: 'National Australia Bank'},
  {name: 'PT Bank Maybank Indonesia'},
  {name: 'Bangkok Bank'},
  {name: 'Krung Thai Bank'},
  {name: 'Bank of Ceylon'},
  {name: 'Hatton National Bank'},
  {name: 'Seylan Bank'},
  {name: 'National Development Bank'},
  {name: 'Commercial Bank of Ceylon'},
  {name: 'DFCC Bank'},
  {name: 'Sampath Bank'},
  {name: 'Nations Trust Bank'},
  {name: 'Union Bank of Colombo'},
  {name: 'Pan Asia Banking Corporation'},
  {name: 'Amana Bank'},
  {name: 'Cargills Bank'},
];
